// data.js

const LANG = {
  en: {
    nav_home: "Home",
    nav_ready: "Am I Ready?",
    nav_apply: "Apply for Voter ID",
    nav_walkthrough: "New Voter Guide",
    nav_journey: "Election Day",
    nav_booth: "Find My Booth",
    nav_reminder: "Set Reminder",
    nav_report: "Report Violation",
    nav_helplines: "Helplines",
    hero_title: "Your Vote. Your Power. Your India.",
    hero_subtitle: "India's most complete election education platform",
    hero_cta_ready: "Am I Ready to Vote? →",
    hero_cta_booth: "Find My Booth →",
    stats_voters: "96.8 Crore Voters",
    stats_seats: "543 Lok Sabha Seats",
    stats_age: "Voting Age: 18+",
    voters_code_title: "The Voter's Oath",
    code_1_title: "🗳️ Your Vote is Sacred",
    code_1_desc: "Every single vote shapes the future of the nation. It is your fundamental right and duty.",
    code_2_title: "⚖️ Choose Wisely",
    code_2_desc: "Research your candidates. Look beyond rhetoric and focus on their track record and vision.",
    code_3_title: "🚫 Reject if Needed",
    code_3_desc: "NOTA (None of the Above) is your power to express dissatisfaction with all listed candidates.",
    code_4_title: "📢 Report Wrongs",
    code_4_desc: "Stand against electoral malpractice. Report bribery, intimidation, or fake news immediately.",
    helpline_text: "📞 Voter Helpline: 1950 | 🌐 voters.eci.gov.in | 📱 cVIGIL App",
    
    // Ready Section
    ready_title: "Am I Ready to Vote?",
    ready_desc: "Let's check your documents to ensure a smooth voting experience.",
    ready_q1: "Do you have your Voter ID (EPIC card)?",
    ready_yes: "YES",
    ready_no: "NO",
    ready_success_title: "You're ready to vote!",
    ready_success_desc: "Your EPIC card is the primary document needed at the polling station.",
    ready_no_epic_title: "Don't have an EPIC card?",
    ready_no_epic_desc: "You can vote if your name is on the electoral roll and you bring any of these 12 alternative documents:",
    
    // Apply Section
    apply_title: "Apply for Voter ID",
    apply_desc: "Select the appropriate form to register or update your details.",
    form6_title: "New Voter (Indian Citizen, 18+)",
    form6a_title: "NRI Voter",
    form8a_title: "Changed Address",
    form8_title: "Correction in Voter ID",
    form6b_title: "Overseas Elector",
    apply_btn: "Apply Online at voters.eci.gov.in →",
    
    // Walkthrough
    walk_title: "New Voter Walkthrough",
    walk_desc: "Follow these 5 steps to become a registered voter.",
    step1_title: "Register Online",
    step1_desc: "New Indian voter (18+)? Fill Form 6 at voters.eci.gov.in. NRI? Fill Form 6A. Changed address? Fill Form 8A. Not sure? Call 1950.",
    step2_title: "Verify Your Details",
    step2_desc: "After submitting, check SMS confirmation. Verify your name appears on the electoral roll.",
    step3_title: "Get Your Voter ID",
    step3_desc: "Download e-EPIC (digital Voter ID) from NVSP portal, or wait for physical card by post.",
    step4_title: "Know Your EVM & NOTA",
    step4_desc: "Press the button next to your candidate. A beep confirms your vote. NOTA is the last option.",
    step5_title: "You're Ready!",
    step5_desc: "You're now a registered voter. Remember — your vote is your voice.",
    
    // Journey
    journey_title: "Election Day Journey",
    journey_desc: "What happens at the polling booth.",
    j1_title: "Booth Opens",
    j1_desc: "Polling booths open at 7 AM. Arrive early.",
    j2_title: "Find Your Name",
    j2_desc: "Officers check the electoral roll.",
    j3_title: "Identity Check",
    j3_desc: "Show your Voter ID or alternate document.",
    j4_title: "Ink on Finger",
    j4_desc: "Indelible ink is applied to your finger.",
    j5_title: "Cast Your Vote on EVM",
    j5_desc: "Press the blue button next to the symbol.",
    j6_title: "VVPAT Confirms Your Vote",
    j6_desc: "A paper slip appears for 7 seconds.",
    j7_title: "NOTA",
    j7_desc: "Your Right to Reject.",
    j8_title: "You've Voted!",
    j8_desc: "Congratulations!",
    
    // Booth
    booth_title: "Find My Booth",
    booth_search: "Search by EPIC No. or Address",
    booth_location: "Use My Location",
    
    // Reminder
    reminder_title: "Set Reminder",
    reminder_desc: "Never miss election day.",
    reminder_btn_cal: "Add to Google Calendar",
    
    // Report
    report_title: "Report a Violation",
    report_desc: "Model Code of Conduct violations threaten the integrity of our elections.",
    
    // Chatbot
    chat_preloaded: [
      { q: "How to get Voter ID?", a: "To get a Voter ID (EPIC card):\n1. Visit **voters.eci.gov.in**\n2. Click **'Register as New Voter'**\n3. Fill **Form 6** (for Indian citizens 18+)\n4. Upload: Age proof (birth certificate or 10th marksheet) + Address proof (Aadhaar, utility bill, or rent agreement) + Passport-size photo\n5. Submit — you'll receive an SMS with your reference number\n6. Download your **e-EPIC** (digital Voter ID) once approved, or wait for the physical card by post.\n\nThe entire process is **free**. Helpline: **1950** | Website: **voters.eci.gov.in**" },
      { q: "I'm an NRI — how do I vote?", a: "As an NRI (Non-Resident Indian), here's how to vote:\n1. Fill **Form 6A** at **voters.eci.gov.in** (not Form 6 — that's for residents)\n2. You must hold a valid **Indian Passport**\n3. You will be registered in the constituency of your **last Indian address**\n4. You must vote **in person** at your assigned booth in India — postal and proxy voting are **not yet available** for NRIs\n5. Plan your travel around election day\n\nDocuments: Indian Passport (mandatory). Helpline: **1950**" },
      { q: "I'm in hostel in another city — can I vote?", a: "Yes! You have **two options**:\n\n**Option 1 — Vote from your home constituency:**\nKeep your registration at your home address. Travel back on election day to cast your vote.\n\n**Option 2 — Register at your hostel city:**\nFill **Form 6** at voters.eci.gov.in with your **hostel address** as your current address. Use your hostel allotment letter or college ID as address proof. Once registered, you can vote at a booth near your hostel.\n\n**Note:** You can only be registered in **one constituency** at a time. If you register at your hostel, your home registration will be removed.\n\nHelpline: **1950** | Website: **voters.eci.gov.in**" },
      { q: "I'm a student — how to register?", a: "If you're **18 years or older**, you can register to vote:\n1. Visit **voters.eci.gov.in** and fill **Form 6**\n2. Choose your registration address — either your **home address** or your **hostel/college address**\n3. Upload documents:\n   - Age proof: 10th marksheet, birth certificate, or Aadhaar\n   - Address proof: Aadhaar, hostel allotment letter, or college bonafide certificate\n   - Passport-size photo\n4. Submit — it's completely **free**\n5. Download your **e-EPIC** once approved\n\n**Tip:** If you register at your hostel address, you can vote locally without traveling home. Helpline: **1950**" },
      { q: "What documents do I need to vote?", a: "Your **Voter ID (EPIC card)** is the primary document. But if you don't have it, ECI accepts **12 alternates** (you need just one):\n1. Aadhaar Card\n2. Passport\n3. Driving License\n4. PAN Card\n5. MNREGA Job Card\n6. Bank/Post Office Passbook with photo\n7. Health Insurance Smart Card (RSBY)\n8. Pension document with photo\n9. Government employee ID\n10. MP/MLA/MLC identity card\n11. NPR Smart Card\n12. Service Identity Card (armed forces)\n\n**Important:** Your name must be on the **electoral roll** regardless of which document you carry. Helpline: **1950**" },
      { q: "How to apply online?", a: "Step-by-step online application:\n1. Go to **voters.eci.gov.in**\n2. Click **'Register as New Voter'** (or 'Login' if you have an account)\n3. Select the correct form:\n   - **Form 6** — New Indian voter (18+)\n   - **Form 6A** — NRI voter\n   - **Form 8A** — Address change\n   - **Form 8** — Correction in existing Voter ID\n4. Fill in your personal details\n5. Upload documents (age proof + address proof + photo)\n6. Submit — you'll get an **SMS confirmation** with a reference number\n7. Track your application status on the same portal\n\nProcessing time: Usually **2-4 weeks**. Helpline: **1950**" },
      { q: "What is NOTA?", a: "**NOTA = None of the Above**\n\nIt's the **last button** on every EVM (Electronic Voting Machine). Use it when:\n- You feel **no candidate** deserves your vote\n- You want to express **dissatisfaction** with all options\n\n**Key facts:**\n- Introduced by the **Supreme Court of India** in September 2013\n- Your vote is still **counted** as democratic participation\n- NOTA votes are recorded but currently do **not** affect the result — even if NOTA gets the most votes, the candidate with the highest votes wins\n- It's your **democratic right** — exercising NOTA is better than not voting at all" },
      { q: "What is cVIGIL?", a: "**cVIGIL** is the Election Commission's official app to report **Model Code of Conduct violations** during elections.\n\n**What you can report:**\n- Cash or gift distribution (bribery)\n- Intimidation or threats\n- Illegal banners, posters, or loudspeakers\n- Misuse of government vehicles\n- Paid news or fake propaganda\n\n**How it works:**\n1. Download from **Play Store** or **App Store**\n2. Click a photo/video of the violation\n3. The app auto-tags your **GPS location** and **timestamp**\n4. Your report reaches the flying squad within **100 minutes**\n5. Your identity is kept **100% confidential**\n\nAlternatively, call the Voter Helpline at **1950**." }
    ]
  },
  hi: {
    nav_home: "होम",
    nav_ready: "क्या मैं तैयार हूं?",
    nav_apply: "वोटर आईडी के लिए आवेदन करें",
    nav_walkthrough: "नया मतदाता गाइड",
    nav_journey: "चुनाव का दिन",
    nav_booth: "मेरा बूथ खोजें",
    nav_reminder: "रिमाइंडर सेट करें",
    nav_report: "उल्लंघन की रिपोर्ट करें",
    nav_helplines: "हेल्पलाइन",
    hero_title: "आपका वोट। आपकी ताकत। आपका भारत।",
    hero_subtitle: "भारत का सबसे पूर्ण चुनाव शिक्षा मंच",
    hero_cta_ready: "क्या मैं वोट देने के लिए तैयार हूँ? →",
    hero_cta_booth: "मेरा बूथ खोजें →",
    stats_voters: "96.8 करोड़ मतदाता",
    stats_seats: "543 लोकसभा सीटें",
    stats_age: "वोटिंग की उम्र: 18+",
    voters_code_title: "मतदाता की शपथ",
    code_1_title: "🗳️ आपका वोट पवित्र है",
    code_1_desc: "हर एक वोट राष्ट्र के भविष्य को आकार देता है। यह आपका मौलिक अधिकार और कर्तव्य है।",
    code_2_title: "⚖️ समझदारी से चुनें",
    code_2_desc: "अपने उम्मीदवारों पर शोध करें। लफ्फाजी से परे देखें और उनके ट्रैक रिकॉर्ड और दृष्टि पर ध्यान दें।",
    code_3_title: "🚫 जरूरत पड़ने पर अस्वीकार करें",
    code_3_desc: "NOTA (इनमें से कोई नहीं) सभी सूचीबद्ध उम्मीदवारों के प्रति असंतोष व्यक्त करने की आपकी शक्ति है।",
    code_4_title: "📢 गलतियों की रिपोर्ट करें",
    code_4_desc: "चुनावी कदाचार के खिलाफ खड़े हों। रिश्वतखोरी, डराने-धमकाने या फर्जी खबरों की तुरंत रिपोर्ट करें।",
    helpline_text: "📞 मतदाता हेल्पलाइन: 1950 | 🌐 voters.eci.gov.in | 📱 cVIGIL ऐप",
    
    // Ready Section
    ready_title: "क्या मैं वोट देने के लिए तैयार हूं?",
    ready_desc: "सुचारू मतदान अनुभव सुनिश्चित करने के लिए आइए आपके दस्तावेज़ों की जांच करें।",
    ready_q1: "क्या आपके पास अपना वोटर आईडी (EPIC कार्ड) है?",
    ready_yes: "हाँ",
    ready_no: "नहीं",
    ready_success_title: "आप वोट देने के लिए तैयार हैं!",
    ready_success_desc: "आपका EPIC कार्ड मतदान केंद्र पर आवश्यक प्राथमिक दस्तावेज़ है।",
    ready_no_epic_title: "EPIC कार्ड नहीं है?",
    ready_no_epic_desc: "आप वोट दे सकते हैं यदि आपका नाम मतदाता सूची में है और आप इनमें से कोई भी 12 वैकल्पिक दस्तावेज़ लाते हैं:",
    
    // Apply Section
    apply_title: "वोटर आईडी के लिए आवेदन करें",
    apply_desc: "पंजीकरण या अपना विवरण अपडेट करने के लिए उपयुक्त फॉर्म का चयन करें।",
    form6_title: "नया मतदाता (भारतीय नागरिक, 18+)",
    form6a_title: "NRI मतदाता",
    form8a_title: "पता बदला गया",
    form8_title: "वोटर आईडी में सुधार",
    form6b_title: "विदेशी निर्वाचक",
    apply_btn: "voters.eci.gov.in पर ऑनलाइन आवेदन करें →",
    
    // Walkthrough
    walk_title: "नया मतदाता वॉकथ्रू",
    walk_desc: "पंजीकृत मतदाता बनने के लिए इन 5 चरणों का पालन करें।",
    step1_title: "ऑनलाइन पंजीकरण करें",
    step1_desc: "नए भारतीय मतदाता (18+)? voters.eci.gov.in पर Form 6 भरें। NRI? Form 6A भरें। पता बदला? Form 8A भरें। संदेह हो? 1950 पर कॉल करें।",
    step2_title: "अपना विवरण सत्यापित करें",
    step2_desc: "सबमिट करने के बाद, SMS पुष्टिकरण की जांच करें। सत्यापित करें कि आपका नाम मतदाता सूची में दिखाई देता है।",
    step3_title: "अपना वोटर आईडी प्राप्त करें",
    step3_desc: "NVSP पोर्टल से ई-ईपीआईसी (डिजिटल वोटर आईडी) डाउनलोड करें, या डाक द्वारा भौतिक कार्ड की प्रतीक्षा करें।",
    step4_title: "अपना EVM और NOTA जानें",
    step4_desc: "अपने उम्मीदवार के बगल वाला बटन दबाएं। एक बीप आपके वोट की पुष्टि करता है। NOTA अंतिम विकल्प है।",
    step5_title: "आप तैयार हैं!",
    step5_desc: "अब आप एक पंजीकृत मतदाता हैं। याद रखें - आपका वोट आपकी आवाज़ है।",
    
    // Journey
    journey_title: "चुनाव के दिन की यात्रा",
    journey_desc: "मतदान केंद्र पर क्या होता है।",
    j1_title: "बूथ खुलता है",
    j1_desc: "मतदान केंद्र सुबह 7 बजे खुलते हैं। जल्दी पहुंचे।",
    j2_title: "अपना नाम खोजें",
    j2_desc: "अधिकारी मतदाता सूची की जांच करते हैं।",
    j3_title: "पहचान की जांच",
    j3_desc: "अपना वोटर आईडी या वैकल्पिक दस्तावेज़ दिखाएं।",
    j4_title: "उंगली पर स्याही",
    j4_desc: "आपकी उंगली पर अमिट स्याही लगाई जाती है।",
    j5_title: "EVM पर अपना वोट डालें",
    j5_desc: "प्रतीक के बगल वाला नीला बटन दबाएं।",
    j6_title: "VVPAT आपके वोट की पुष्टि करता है",
    j6_desc: "एक पेपर स्लिप 7 सेकंड के लिए दिखाई देती है।",
    j7_title: "NOTA",
    j7_desc: "अस्वीकार करने का आपका अधिकार।",
    j8_title: "आपने वोट दिया है!",
    j8_desc: "बधाई हो!",
    
    // Booth
    booth_title: "मेरा बूथ खोजें",
    booth_search: "EPIC नंबर या पते से खोजें",
    booth_location: "मेरे स्थान का उपयोग करें",
    
    // Reminder
    reminder_title: "रिमाइंडर सेट करें",
    reminder_desc: "चुनाव का दिन कभी न भूलें।",
    reminder_btn_cal: "Google कैलेंडर में जोड़ें",
    
    // Report
    report_title: "उल्लंघन की रिपोर्ट करें",
    report_desc: "आदर्श आचार संहिता का उल्लंघन हमारे चुनावों की अखंडता को खतरे में डालता है।",
    
    chat_welcome: "नमस्ते! मैं मतदान AI हूं। आज आपकी चुनाव संबंधी जानकारी में कैसे मदद करूं?",
    chat_preloaded: [
      { q: "वोटर ID कैसे बनाएं?", a: "वोटर ID (EPIC कार्ड) बनाने के लिए:\n1. **voters.eci.gov.in** पर जाएं\n2. **'नए मतदाता के रूप में पंजीकरण करें'** पर क्लिक करें\n3. **Form 6** भरें (भारतीय नागरिक 18+)\n4. अपलोड करें: आयु प्रमाण (जन्म प्रमाण पत्र या 10वीं मार्कशीट) + पता प्रमाण (आधार, बिजली बिल) + पासपोर्ट फोटो\n5. सबमिट करें — आपको SMS से रेफरेंस नंबर मिलेगा\n6. स्वीकृति के बाद **e-EPIC** (डिजिटल वोटर ID) डाउनलोड करें\n\nयह प्रक्रिया पूरी तरह **मुफ़्त** है। हेल्पलाइन: **1950**" },
      { q: "मैं एक NRI हूँ — मैं कैसे वोट करूँ?", a: "NRI (अनिवासी भारतीय) के रूप में वोट करने के लिए:\n1. **voters.eci.gov.in** पर **Form 6A** भरें (Form 6 नहीं — वह निवासियों के लिए है)\n2. आपके पास वैध **भारतीय पासपोर्ट** होना चाहिए\n3. आपका पंजीकरण आपके **अंतिम भारतीय पते** के निर्वाचन क्षेत्र में होगा\n4. आपको भारत में अपने बूथ पर **व्यक्तिगत रूप से** मतदान करना होगा — NRI के लिए डाक/प्रॉक्सी वोटिंग **अभी उपलब्ध नहीं** है\n\nदस्तावेज: भारतीय पासपोर्ट (अनिवार्य)। हेल्पलाइन: **1950**" },
      { q: "मैं दूसरे शहर में हॉस्टल में हूँ — क्या मैं वोट कर सकता हूँ?", a: "हाँ! आपके पास **दो विकल्प** हैं:\n\n**विकल्प 1 — अपने गृह निर्वाचन क्षेत्र से वोट करें:**\nअपना पंजीकरण घर के पते पर रखें। चुनाव के दिन वापस जाकर वोट करें।\n\n**विकल्प 2 — हॉस्टल शहर में पंजीकरण करें:**\nvoters.eci.gov.in पर **Form 6** भरें, अपने **हॉस्टल का पता** दें। हॉस्टल आवंटन पत्र या कॉलेज ID पता प्रमाण के रूप में उपयोग करें। पंजीकरण के बाद हॉस्टल के पास वोट कर सकते हैं।\n\n**ध्यान दें:** आप एक समय में केवल **एक निर्वाचन क्षेत्र** में पंजीकृत हो सकते हैं। हेल्पलाइन: **1950**" },
      { q: "मैं एक छात्र हूँ — कैसे पंजीकरण करूँ?", a: "यदि आपकी उम्र **18 वर्ष या अधिक** है:\n1. **voters.eci.gov.in** पर **Form 6** भरें\n2. पंजीकरण पता चुनें — **घर का पता** या **हॉस्टल/कॉलेज का पता**\n3. दस्तावेज अपलोड करें:\n   - आयु प्रमाण: 10वीं मार्कशीट, जन्म प्रमाण पत्र, या आधार\n   - पता प्रमाण: आधार, हॉस्टल आवंटन पत्र, या कॉलेज बोनाफाइड\n4. सबमिट करें — यह पूरी तरह **मुफ़्त** है\n\n**सुझाव:** हॉस्टल पते पर पंजीकरण करें तो बिना घर गए स्थानीय रूप से वोट कर सकते हैं। हेल्पलाइन: **1950**" },
      { q: "वोट देने के लिए मुझे किन दस्तावेजों की आवश्यकता है?", a: "**वोटर ID (EPIC कार्ड)** प्राथमिक दस्तावेज है। लेकिन न होने पर ECI **12 विकल्प** स्वीकार करता है:\n1. आधार कार्ड\n2. पासपोर्ट\n3. ड्राइविंग लाइसेंस\n4. पैन कार्ड\n5. मनरेगा जॉब कार्ड\n6. फोटो वाली बैंक पासबुक\n7. स्वास्थ्य बीमा स्मार्ट कार्ड\n8. फोटो वाला पेंशन दस्तावेज\n9. सरकारी कर्मचारी ID\n10. सांसद/विधायक ID\n11. NPR स्मार्ट कार्ड\n12. सेवा पहचान पत्र (सशस्त्र बल)\n\n**महत्वपूर्ण:** कोई भी दस्तावेज लाएं, आपका नाम **मतदाता सूची** में होना ज़रूरी है। हेल्पलाइन: **1950**" },
      { q: "ऑनलाइन आवेदन कैसे करें?", a: "ऑनलाइन आवेदन की प्रक्रिया:\n1. **voters.eci.gov.in** पर जाएं\n2. सही फॉर्म चुनें:\n   - **Form 6** — नया भारतीय मतदाता (18+)\n   - **Form 6A** — NRI मतदाता\n   - **Form 8A** — पता बदलाव\n   - **Form 8** — वोटर ID में सुधार\n3. व्यक्तिगत विवरण भरें\n4. दस्तावेज अपलोड करें (आयु प्रमाण + पता प्रमाण + फोटो)\n5. सबमिट करें — **SMS पुष्टिकरण** मिलेगा\n6. उसी पोर्टल पर स्थिति ट्रैक करें\n\nप्रोसेसिंग समय: आमतौर पर **2-4 सप्ताह**। हेल्पलाइन: **1950**" },
      { q: "NOTA क्या है?", a: "**NOTA = इनमें से कोई नहीं**\n\nयह EVM पर **अंतिम बटन** है। इसका उपयोग करें जब:\n- आपको लगता है कि **कोई भी उम्मीदवार** योग्य नहीं है\n- आप सभी विकल्पों से **असंतोष** व्यक्त करना चाहते हैं\n\n**मुख्य तथ्य:**\n- **2013** में सुप्रीम कोर्ट द्वारा शुरू किया गया\n- आपका वोट लोकतांत्रिक भागीदारी के रूप में **गिना** जाता है\n- NOTA वोट दर्ज होते हैं लेकिन वर्तमान में परिणाम को **प्रभावित नहीं** करते\n- वोट न देने से NOTA दबाना **बेहतर** है" },
      { q: "cVIGIL क्या है?", a: "**cVIGIL** चुनाव आयोग का आधिकारिक ऐप है जो **आदर्श आचार संहिता के उल्लंघन** की रिपोर्ट करता है।\n\n**क्या रिपोर्ट कर सकते हैं:**\n- नकद या उपहार वितरण (रिश्वत)\n- डराना-धमकाना\n- अवैध बैनर, पोस्टर, लाउडस्पीकर\n- सरकारी वाहनों का दुरुपयोग\n\n**कैसे काम करता है:**\n1. **Play Store** या **App Store** से डाउनलोड करें\n2. उल्लंघन की फोटो/वीडियो लें\n3. ऐप स्वचालित रूप से **GPS स्थान** टैग करता है\n4. आपकी रिपोर्ट **100 मिनट** के भीतर फ्लाइंग स्क्वॉड तक पहुंचती है\n5. आपकी पहचान **100% गोपनीय** रहती है\n\nवैकल्पिक: **1950** पर कॉल करें।" }
    ]
  },
  kn: {
    nav_home: "ಮುಖಪುಟ",
    nav_ready: "ನಾನು ಸಿದ್ಧನಾಗಿದ್ದೇನೆಯೇ?",
    nav_apply: "ಮತದಾರರ ID ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    nav_walkthrough: "ಹೊಸ ಮತದಾರರ ಮಾರ್ಗದರ್ಶಿ",
    nav_journey: "ಚುನಾವಣಾ ದಿನ",
    nav_booth: "ನನ್ನ ಬೂತ್ ಹುಡುಕಿ",
    nav_reminder: "ಜ್ಞಾಪನೆ ಹೊಂದಿಸಿ",
    nav_report: "ಉಲ್ಲಂಘನೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    nav_helplines: "ಸಹಾಯವಾಣಿಗಳು",
    hero_title: "ನಿಮ್ಮ ಮತ. ನಿಮ್ಮ ಶಕ್ತಿ. ನಿಮ್ಮ ಭಾರತ.",
    hero_subtitle: "ಭಾರತದ ಅತ್ಯಂತ ಸಂಪೂರ್ಣ ಚುನಾವಣಾ ಶಿಕ್ಷಣ ವೇದಿಕೆ",
    hero_cta_ready: "ನಾನು ಮತ ಚಲಾಯಿಸಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆಯೇ? →",
    hero_cta_booth: "ನನ್ನ ಬೂತ್ ಹುಡುಕಿ →",
    stats_voters: "96.8 ಕೋಟಿ ಮತದಾರರು",
    stats_seats: "543 ಲೋಕಸಭಾ ಸ್ಥಾನಗಳು",
    stats_age: "ಮತದಾನದ ವಯಸ್ಸು: 18+",
    voters_code_title: "ಮತದಾರರ ಪ್ರತಿಜ್ಞೆ",
    code_1_title: "🗳️ ನಿಮ್ಮ ಮತ ಪವಿತ್ರವಾಗಿದೆ",
    code_1_desc: "ಪ್ರತಿಯೊಂದು ಮತವೂ ರಾಷ್ಟ್ರದ ಭವಿಷ್ಯವನ್ನು ರೂಪಿಸುತ್ತದೆ. ಇದು ನಿಮ್ಮ ಮೂಲಭೂತ ಹಕ್ಕು ಮತ್ತು ಕರ್ತವ್ಯ.",
    code_2_title: "⚖️ ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಆರಿಸಿ",
    code_2_desc: "ನಿಮ್ಮ ಅಭ್ಯರ್ಥಿಗಳನ್ನು ಸಂಶೋಧಿಸಿ. ಅವರ ಟ್ರ್ಯಾಕ್ ರೆಕಾರ್ಡ್ ಮತ್ತು ದೃಷ್ಟಿಯ ಮೇಲೆ ಗಮನಹರಿಸಿ.",
    code_3_title: "🚫 ಅಗತ್ಯವಿದ್ದರೆ ತಿರಸ್ಕರಿಸಿ",
    code_3_desc: "NOTA (ಮೇಲಿನ ಯಾವುದೂ ಅಲ್ಲ) ಪಟ್ಟಿ ಮಾಡಲಾದ ಎಲ್ಲಾ ಅಭ್ಯರ್ಥಿಗಳ ಬಗ್ಗೆ ಅಸಮಾಧಾನವನ್ನು ವ್ಯಕ್ತಪಡಿಸುವ ನಿಮ್ಮ ಶಕ್ತಿಯಾಗಿದೆ.",
    code_4_title: "📢 ತಪ್ಪುಗಳನ್ನು ವರದಿ ಮಾಡಿ",
    code_4_desc: "ಚುನಾವಣಾ ಅಕ್ರಮಗಳ ವಿರುದ್ಧ ನಿಲ್ಲಿರಿ. ಲಂಚ, ಬೆದರಿಕೆ ಅಥವಾ ನಕಲಿ ಸುದ್ದಿಗಳನ್ನು ತಕ್ಷಣ ವರದಿ ಮಾಡಿ.",
    helpline_text: "📞 ಮತದಾರರ ಸಹಾಯವಾಣಿ: 1950 | 🌐 voters.eci.gov.in | 📱 cVIGIL ಅಪ್ಲಿಕೇಶನ್",
    
    // Ready Section
    ready_title: "ನಾನು ಮತ ಚಲಾಯಿಸಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆಯೇ?",
    ready_desc: "ಸುಗಮ ಮತದಾನದ ಅನುಭವವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸೋಣ.",
    ready_q1: "ನಿಮ್ಮ ಬಳಿ ಮತದಾರರ ID (EPIC ಕಾರ್ಡ್) ಇದೆಯೇ?",
    ready_yes: "ಹೌದು",
    ready_no: "ಇಲ್ಲ",
    ready_success_title: "ನೀವು ಮತ ಚಲಾಯಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಿ!",
    ready_success_desc: "ನಿಮ್ಮ EPIC ಕಾರ್ಡ್ ಮತಗಟ್ಟೆಯಲ್ಲಿ ಅಗತ್ಯವಿರುವ ಪ್ರಾಥಮಿಕ ದಾಖಲೆಯಾಗಿದೆ.",
    ready_no_epic_title: "EPIC ಕಾರ್ಡ್ ಇಲ್ಲವೇ?",
    ready_no_epic_desc: "ಮತದಾರರ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರಿದ್ದರೆ ಮತ್ತು ಈ 12 ಪರ್ಯಾಯ ದಾಖಲೆಗಳಲ್ಲಿ ಯಾವುದನ್ನಾದರೂ ತಂದರೆ ನೀವು ಮತ ಚಲಾಯಿಸಬಹುದು:",
    
    // Apply Section
    apply_title: "ಮತದಾರರ ID ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    apply_desc: "ನೋಂದಾಯಿಸಲು ಅಥವಾ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಲು ಸೂಕ್ತವಾದ ಫಾರ್ಮ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    form6_title: "ಹೊಸ ಮತದಾರ (ಭಾರತೀಯ ನಾಗರಿಕ, 18+)",
    form6a_title: "NRI ಮತದಾರ",
    form8a_title: "ವಿಳಾಸ ಬದಲಾವಣೆ",
    form8_title: "ಮತದಾರರ ID ಯಲ್ಲಿ ತಿದ್ದುಪಡಿ",
    form6b_title: "ಸಾಗರೋತ್ತರ ಮತದಾರ",
    apply_btn: "voters.eci.gov.in ನಲ್ಲಿ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ →",
    
    // Walkthrough
    walk_title: "ಹೊಸ ಮತದಾರರ ವೀಕ್ಷಣೆ",
    walk_desc: "ನೋಂದಾಯಿತ ಮತದಾರರಾಗಲು ಈ 5 ಹಂತಗಳನ್ನು ಅನುಸರಿಸಿ.",
    step1_title: "ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ನೋಂದಾಯಿಸಿ",
    step1_desc: "ಹೊಸ ಭಾರತೀಯ ಮತದಾರ (18+)? voters.eci.gov.in ನಲ್ಲಿ Form 6 ಭರ್ತಿ ಮಾಡಿ. NRI? Form 6A. ವಿಳಾಸ ಬದಲಾಗಿದೆಯೇ? Form 8A. ಖಚಿತವಿಲ್ಲವೇ? 1950 ಗೆ ಕರೆ ಮಾಡಿ.",
    step2_title: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    step2_desc: "ಸಲ್ಲಿಸಿದ ನಂತರ, SMS ದೃಢೀಕರಣವನ್ನು ಪರಿಶೀಲಿಸಿ. ಮತದಾರರ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರು ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸಿ.",
    step3_title: "ನಿಮ್ಮ ಮತದಾರರ ID ಪಡೆಯಿರಿ",
    step3_desc: "NVSP ಪೋರ್ಟಲ್‌ನಿಂದ ಇ-ಇಪಿಐಸಿ (ಡಿಜಿಟಲ್ ಮತದಾರರ ID) ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ, ಅಥವಾ ಅಂಚೆ ಮೂಲಕ ಭೌತಿಕ ಕಾರ್ಡ್‌ಗಾಗಿ ಕಾಯಿರಿ.",
    step4_title: "ನಿಮ್ಮ EVM ಮತ್ತು NOTA ತಿಳಿಯಿರಿ",
    step4_desc: "ನಿಮ್ಮ ಅಭ್ಯರ್ಥಿಯ ಪಕ್ಕದಲ್ಲಿರುವ ಬಟನ್ ಒತ್ತಿರಿ. ಬೀಪ್ ಶಬ್ದ ನಿಮ್ಮ ಮತವನ್ನು ದೃಢೀಕರಿಸುತ್ತದೆ. NOTA ಕೊನೆಯ ಆಯ್ಕೆಯಾಗಿದೆ.",
    step5_title: "ನೀವು ಸಿದ್ಧರಿದ್ದೀರಿ!",
    step5_desc: "ನೀವು ಈಗ ನೋಂದಾಯಿತ ಮತದಾರರಾಗಿದ್ದೀರಿ. ನೆನಪಿಡಿ - ನಿಮ್ಮ ಮತ ನಿಮ್ಮ ಧ್ವನಿ.",
    
    // Journey
    journey_title: "ಚುನಾವಣಾ ದಿನದ ಪ್ರಯಾಣ",
    journey_desc: "ಮತಗಟ್ಟೆಯಲ್ಲಿ ಏನಾಗುತ್ತದೆ.",
    j1_title: "ಬೂತ್ ತೆರೆಯುತ್ತದೆ",
    j1_desc: "ಮತಗಟ್ಟೆಗಳು ಬೆಳಿಗ್ಗೆ 7 ಗಂಟೆಗೆ ತೆರೆಯುತ್ತವೆ. ಬೇಗ ಬನ್ನಿ.",
    j2_title: "ನಿಮ್ಮ ಹೆಸರನ್ನು ಹುಡುಕಿ",
    j2_desc: "ಅಧಿಕಾರಿಗಳು ಮತದಾರರ ಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.",
    j3_title: "ಗುರುತಿನ ಪರಿಶೀಲನೆ",
    j3_desc: "ನಿಮ್ಮ ಮತದಾರರ ID ಅಥವಾ ಪರ್ಯಾಯ ದಾಖಲೆಯನ್ನು ತೋರಿಸಿ.",
    j4_title: "ಬೆರಳಿಗೆ ಶಾಯಿ",
    j4_desc: "ನಿಮ್ಮ ಬೆರಳಿಗೆ ಅಳಿಸಲಾಗದ ಶಾಯಿಯನ್ನು ಹಚ್ಚಲಾಗುತ್ತದೆ.",
    j5_title: "EVM ನಲ್ಲಿ ನಿಮ್ಮ ಮತ ಚಲಾಯಿಸಿ",
    j5_desc: "ಚಿಹ್ನೆಯ ಪಕ್ಕದಲ್ಲಿರುವ ನೀಲಿ ಬಟನ್ ಒತ್ತಿರಿ.",
    j6_title: "VVPAT ನಿಮ್ಮ ಮತವನ್ನು ದೃಢೀಕರಿಸುತ್ತದೆ",
    j6_desc: "ಕಾಗದದ ಚೀಟಿ 7 ಸೆಕೆಂಡುಗಳ ಕಾಲ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ.",
    j7_title: "NOTA",
    j7_desc: "ತಿರಸ್ಕರಿಸುವ ನಿಮ್ಮ ಹಕ್ಕು.",
    j8_title: "ನೀವು ಮತ ಚಲಾಯಿಸಿದ್ದೀರಿ!",
    j8_desc: "ಅಭಿನಂದನೆಗಳು!",
    
    // Booth
    booth_title: "ನನ್ನ ಬೂತ್ ಹುಡುಕಿ",
    booth_search: "EPIC ಸಂಖ್ಯೆ ಅಥವಾ ವಿಳಾಸದ ಮೂಲಕ ಹುಡುಕಿ",
    booth_location: "ನನ್ನ ಸ್ಥಳವನ್ನು ಬಳಸಿ",
    
    // Reminder
    reminder_title: "ಜ್ಞಾಪನೆ ಹೊಂದಿಸಿ",
    reminder_desc: "ಚುನಾವಣಾ ದಿನವನ್ನು ಎಂದಿಗೂ ತಪ್ಪಿಸಿಕೊಳ್ಳಬೇಡಿ.",
    reminder_btn_cal: "Google ಕ್ಯಾಲೆಂಡರ್‌ಗೆ ಸೇರಿಸಿ",
    
    // Report
    report_title: "ಉಲ್ಲಂಘನೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    report_desc: "ಮಾದರಿ ನೀತಿ ಸಂಹಿತೆ ಉಲ್ಲಂಘನೆಗಳು ನಮ್ಮ ಚುನಾವಣೆಗಳ ಸಮಗ್ರತೆಗೆ ಬೆದರಿಕೆ ಹಾಕುತ್ತವೆ.",
    
    chat_welcome: "ನಮಸ್ಕಾರ! ನಾನು ಮತದಾನ AI. ಇಂದು ಚುನಾವಣೆ ಸಂಬಂಧಿ ಪ್ರಶ್ನೆಗಳಲ್ಲಿ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
    chat_preloaded: [
      { q: "ಮತದಾರರ ID ಹೇಗೆ ಪಡೆಯುವುದು?", a: "ಮತದಾರರ ID (EPIC ಕಾರ್ಡ್) ಗಾಗಿ voters.eci.gov.in ಗೆ ಭೇಟಿ ನೀಡಿ ಮತ್ತು Form 6 ಭರ್ತಿ ಮಾಡಿ. ಅಗತ್ಯ ದಾಖಲೆಗಳು: ವಯಸ್ಸಿನ ಪ್ರಮಾಣ, ವಿಳಾಸ ಪ್ರಮಾಣ, ಪಾಸ್ಪೋರ್ಟ್ ಫೋಟೋ. ಇದು ಉಚಿತ. ಹೆಲ್ಪ್ಲೈನ್: 1950" },
      { q: "ನಾನು NRI — ನಾನು ಹೇಗೆ ಮತ ಚಲಾಯಿಸುವುದು?", a: "NRI ಮತದಾರರು voters.eci.gov.in ನಲ್ಲಿ Form 6A ಭರ್ತಿ ಮಾಡಬೇಕು. ನೀವು ಭಾರತೀಯ ನಾಗರಿಕರಾಗಿರಬೇಕು. ನೀವು ಭಾರತದಲ್ಲಿನ ನಿಮ್ಮ ಕ್ಷೇತ್ರದಲ್ಲಿ ಮಾತ್ರ ಖುದ್ದಾಗಿ ಮತ ಚಲಾಯಿಸಬಹುದು. ದಾಖಲೆಗಳು: ಭಾರತೀಯ ಪಾಸ್‌ಪೋರ್ಟ್. ಸಹಾಯವಾಣಿ: 1950" },
      { q: "ನಾನು ಬೇರೆ ಊರಿನ ಹಾಸ್ಟೆಲ್ ನಲ್ಲಿದ್ದೇನೆ — ಮತ ಹಾಕಬಹುದೇ?", a: "ಹೌದು, ನಿಮಗೆ ಎರಡು ಆಯ್ಕೆಗಳಿವೆ: 1) ನಿಮ್ಮ ಸ್ವಂತ ಊರಿನಲ್ಲಿ ಮತ ಚಲಾಯಿಸಿ (ಚುನಾವಣೆಯ ದಿನದಂದು ಪ್ರಯಾಣಿಸಿ) ಅಥವಾ 2) Form 6 ಅನ್ನು ಭರ್ತಿ ಮಾಡುವ ಮೂಲಕ ನಿಮ್ಮ ಪ್ರಸ್ತುತ ನಗರದ ವಿಳಾಸದಲ್ಲಿ ನೋಂದಾಯಿಸಿ. ಸಹಾಯವಾಣಿ: 1950" },
      { q: "ನಾನು ವಿದ್ಯಾರ್ಥಿ — ನೋಂದಾಯಿಸುವುದು ಹೇಗೆ?", a: "ನಿಮಗೆ 18+ ವರ್ಷವಾಗಿದ್ದರೆ, voters.eci.gov.in ನಲ್ಲಿ Form 6 ಭರ್ತಿ ಮಾಡಿ. ನಿಮ್ಮ ಮನೆಯ ವಿಳಾಸ ಅಥವಾ ಹಾಸ್ಟೆಲ್/ಕಾಲೇಜು ವಿಳಾಸದಲ್ಲಿ ನೋಂದಾಯಿಸಬಹುದು. ಇದು ಉಚಿತ! ಸಹಾಯವಾಣಿ: 1950" },
      { q: "ಮತದಾನ ಮಾಡಲು ಯಾವ ದಾಖಲೆಗಳು ಬೇಕು?", a: "ಮತದಾರರ ID (EPIC) ಉತ್ತಮ. ಆದರೆ ECI 12 ಪರ್ಯಾಯಗಳನ್ನು ಸ್ವೀಕರಿಸುತ್ತದೆ: ಆಧಾರ್, ಪಾಸ್‌ಪೋರ್ಟ್, ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್, ಪ್ಯಾನ್ ಕಾರ್ಡ್, MNREGA ಜಾಬ್ ಕಾರ್ಡ್, ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್, ಸ್ಮಾರ್ಟ್ ಕಾರ್ಡ್. ಸಹಾಯವಾಣಿ: 1950" },
      { q: "ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು ಹೇಗೆ?", a: "voters.eci.gov.in ಗೆ ಹೋಗಿ → 'ಹೊಸ ಮತದಾರರಾಗಿ ನೋಂದಾಯಿಸಿ' ಕ್ಲಿಕ್ ಮಾಡಿ → Form 6 ಭರ್ತಿ ಮಾಡಿ → ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ → ಸಲ್ಲಿಸಿ. ನಿಮಗೆ SMS ಬರುತ್ತದೆ. ಸಹಾಯವಾಣಿ: 1950" },
      { q: "NOTA ಎಂದರೇನು?", a: "NOTA = ಮೇಲಿನ ಯಾವುದೂ ಅಲ್ಲ. ಇದು EVM ನಲ್ಲಿನ ಕೊನೆಯ ಆಯ್ಕೆಯಾಗಿದೆ. ಯಾವ ಅಭ್ಯರ್ಥಿಯೂ ನಿಮ್ಮ ಮತಕ್ಕೆ ಅರ್ಹರಲ್ಲ ಎಂದು ನೀವು ಭಾವಿಸಿದರೆ, NOTA ಒತ್ತಿರಿ." },
      { q: "cVIGIL ಎಂದರೇನು?", a: "cVIGIL ಎಂಬುದು ಚುನಾವಣಾ ನೀತಿ ಸಂಹಿತೆ ಉಲ್ಲಂಘನೆಗಳನ್ನು ವರದಿ ಮಾಡುವ ಅಪ್ಲಿಕೇಶನ್ ಆಗಿದೆ - ಲಂಚ, ಬೆದರಿಕೆ, ಅಕ್ರಮ ಬ್ಯಾನರ್‌ಗಳು. ಪ್ಲೇ ಸ್ಟೋರ್‌ನಿಂದ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ. ಸಹಾಯವಾಣಿ: 1950" }
    ]
  }
};
